# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_auto_20160816_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='mid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
